volumes:
    caddy_data:
    caddy_config:

services:
    caddy:
        container_name: caddy
        image: caddy:2.9.1-alpine
        restart: unless-stopped
        volumes:
            - caddy_data:/data
            - caddy_config:/config
            - ./caddy/snippets:/etc/caddy/snippets:ro
            - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
            - ../src:/var/www/html
        ports:
            - 80:80
            - 443:443
            - 443:443/udp
        healthcheck:
            test: ["CMD", "wget", "--no-check-certificate", "--spider", "https://localhost/healthcheck"]
            interval: 30s
            timeout: 1s
            retries: 3
            start_period: 10s
            #start_interval: 2s

    app1:
        container_name: app1
        restart: unless-stopped
        tty: true

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:4.1.3-management-alpine
        restart: unless-stopped
        ports:
            - 5672:5672
            - 15672:15672
