name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    env:
      ENV: DEVELOPMENT

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: ['8.4']
        composer-version: [v2]
        dependency-version: [prefer-lowest, prefer-stable]

    name: ${{ matrix.php }} - ${{ matrix.os }} - Composer ${{ matrix.composer-version }} --${{ matrix.dependency-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
            path: ~/.composer/cache/files
            key: dependencies-php-${{ matrix.php }}-composer-${{ matrix.composer-version }}-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: zip
          coverage: pcov
          tools: composer:${{ matrix.composer-version }}

      - name: Validate composer.json and composer.lock
        run: composer validate --working-dir=. --strict

      - name: Install PHP dependencies
        run: composer update --${{ matrix.dependency-version }} --ansi  --no-interaction --prefer-dist

      - name: Check PHP Syntax
        run: composer check-syntax

      - name: Check Coding Standards
        run: composer check-style

#      - name: Check with PHPStan
#        run: composer phpstan

      - name: Check Test Cases
        run: composer test
